
CREATE TABLE Addresses(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	addressid NVARCHAR(1000) NOT NULL,
	address1 NVARCHAR(1000) NOT NULL,
	address2 NVARCHAR(1000),
	city NVARCHAR(1000) NOT NULL,
	state NVARCHAR(1000) NOT NULL,
	zipcode NVARCHAR(1000) NOT NULL,
)

CREATE TABLE Users(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	addressid INT NOT NULL FOREIGN KEY REFERENCES Addresses(id),
	username NVARCHAR(255) NOT NULL,
	userpassword NVARCHAR(255) NOT NULL,
	email NVARCHAR(255) NOT NULL,
)


CREATE TABLE Genre(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	genre NVARCHAR(255) NOT NULL, 
)

CREATE TABLE Books(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	title NVARCHAR(255) NOT NULL, 
	author NVARCHAR(255) NOT NULL,
	isbn NVARCHAR(255) NOT NULL,
	genre int NOT NULL FOREIGN KEY REFERENCES Genre(id),
) 




CREATE TABLE Status_Codes(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	statuscode NVARCHAR NOT NULL UNIQUE ,

)

CREATE TABLE Owned_Books(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	userid INT NOT NULL FOREIGN KEY REFERENCES Users(id),
	bookid INT NOT NULL FOREIGN KEY REFERENCES Books(id),
	condition NVARCHAR(255) NOT NULL, 
	availability int NOT NULL FOREIGN KEY REFERENCES Status_Codes(id),
)



CREATE TABLE Loans(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	userid INT NOT NULL FOREIGN KEY REFERENCES Users(id),
	owned_bookid INT NOT NULL FOREIGN KEY REFERENCES Owned_Books(id),
	message  NTEXT NOT NULL,
	acceptance_status int NOT NULL FOREIGN KEY REFERENCES Status_Codes(id),
	ispublic BIT NOT NULL,
	dropoffdate DATETIME NOT NULL, 
	returneddate DATETIME NOT NULL, 
)

CREATE TABLE Loaned_Books(
	id INT PRIMARY KEY IDENTITY NOT NULL,
	owned_bookid INT NOT NULL FOREIGN KEY REFERENCES Owned_Books(id),
	loanid INT NOT NULL FOREIGN KEY REFERENCES Loans(id),
)


